name: discover_printers
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  esc_pos_printer:
    path: ../../
  esc_pos_utils:
    git: https://github.com/kahero-team/esc_pos_utils_ticket.git
  flutter:
    sdk: flutter
  image: ^3.0.2
  intl: ^0.16.1
  path_provider: ^1.6.5
  ping_discover_network: ^0.2.0+1
  qr_flutter: ^3.2.0
  wifi: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/rabbit_black.jpg