name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 3.1.5
homepage: https://github.com/andrey-ushakov/esc_pos_printer
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  escposprinter:
    git: https://github.com/kahero-team/escposprinter
  esc_pos_utils:
    git: https://github.com/kahero-team/esc_pos_utils_ticket.git
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
